#version: "3.7"
#services:
#  db:
#    image: postgres:16
#    command: -p 1221
#    expose:
#      - 1221
#    env_file:
#      - .env-non-dev
#  app:
#    build:
#      context: .
#    env_file:
#      - .env-non-dev
#    container_name: fastapi_app
#    command: ["/fastapi_app/docker_/app.sh"]
#    ports:
#      - 9999:8000
#    depends_on:
#      - db
