"""new6

Revision ID: 6ebb99a9223e
Revises: 536e0ff1bdde
Create Date: 2024-04-29 16:08:41.606042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebb99a9223e'
down_revision: Union[str, None] = '536e0ff1bdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('order', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'email')
    # ### end Alembic commands ###
